--[[
Pinta la sintaxis del codigo
--]]
return {
  "nvim-treesitter/nvim-treesitter",
  main = "nvim-treesitter.configs",
  opts = {
    ensure_installed = {
      "bash",
      "cpp",
      "make",
      "cmake",
      "css",
      "cuda",
      "gdscript",
      "gdshader",
      "godot_resource",
      "glsl",
      "dockerfile",
      "go",
      "groovy",
      "helm",
      "nginx",
      "html",
      "htmldjango",
      "passwd",
      "php",
      "kconfig",
      "java",
      "javascript",
      "r",
      "ruby",
      "robots",
      "requirements",
      "sql",
      "hcl",
      "rust",
      "vue",
      "wgsl",
      "python",
      "typescript",
      "latex",
      "ini",
      "csv",
      "xml",
      "json",
      "toml",
      "yaml",
    },
    highlight = {
      enable = true
    },
  },
}
